# Generated by Django 5.0.3 on 2024-03-21 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('telefon_raqami', models.CharField(max_length=15)),
                ('parol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Chegirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chegirma_foizi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chegirma_muddati', models.DateField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.PositiveIntegerField()),
                ('narxi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.mahsulot')),
                ('foydalanuvchi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.users')),
            ],
        ),
    ]
